### ISSUE TITLE
wwwroot\override\override/controllers/front not writable

### ISSUE THREAD

**Issue by Sting55** [nenes25/eicaptcha#101]
### Your prestashop version
1.6.0.9
### Eicaptcha Version
0.4.16
### Do you use a specific theme
no
### Issue description
After installation, the following red message appears:
The overlay can not be installed: The directory (... wwwroot \ override \ override / controllers / front) is not writable

**Comment by nenes25** [comment]
Hi,

This issue is related with your hosting.
During the installation of the module prestashop try to install an override in the directory wwwroot \ override \ override / controllers / front , but it does not have the rights to do it.
Please add the necessary rights on this dir for the user running prestashop ( often it is www-data if your stack use apache )
If you're not comfortable with that you'll have to check with your hosting provider.

Regards,
