### ISSUE TITLE
No such file or directory in...

### ISSUE THREAD

**Issue by magneticlab-ch** [nenes25/eicaptcha#11]
Hi,

There is a strange mention to vendor/autoload.php in eicaptch/eicaptcha.php on line 382

`require_once(__DIR__ . '/vendor/autoload.php');`

but this file do not exist in the module files...

**Comment by nenes25** [comment]
Hello,

Thanks for your feedback but as written in the module README

__ 
"The last version used composer to get recaptcha lib.
If you clone the repository don't forget to use composer update in order to download the necessary recaptcha composer package. Otherwise you could download the last release wich bundle all necessary files."
__ 

I guess that you didn't notice theses lines ;)

Regards,
Hervé

**Comment by magneticlab-ch** [comment]
Well, thanks for this quick answer.

but if you follow simply the tutorial on [this page](https://www.h-hennes.fr/blog/module-recaptcha-pour-le-formulaire-de-contact-prestashop/) as mentionned in the README then you can directly download the module and there is no mention to composer.

Most of PrestaShop user don't even know how to use composer. they just know how to install a module via the backend.

Even the zip file for prestashop 1.6 isn't correctly formed. the directory name should be the same as the main module file. ex. directory eicaptcha-master and eicaptch-master.php instead of eicaptcha.php.

Otherwise the module works fine.

**Comment by nenes25** [comment]
I know this issue with the zip, which is related to the way github make the zip archive.

I should make a deployment script which will bundle all necessaries datas in one place, but for now i have not enough time and it's not on the top of my priorities ;-)

I will let this issue open as a reminder
