### ISSUE TITLE
Problem with the EICAPTCHA module

### ISSUE THREAD

**Issue by Manuel-CJ** [nenes25/eicaptcha#112]
Prestashop Version: 1.6.1.18

Eicaptcha version: 0.4.17

I have installed the eicaptcha module and it works for me when creating an account, but in the contact form it does not appear and if I try to send a message, it tells me an error.

Error 1
incorrect response to CAPTCHA challenge. Please try again.

In the console they tell me the following errors:

recaptcha__es.js: 523 Uncaught Error: reCAPTCHA placeholder element must be an element or id
     at Object.nU [as render] (recaptcha__es.js: 523)
     at onloadCallback (contact us: 5)
     at aQ (recaptcha__es.js: 529)
     at xE (recaptcha__es.js: 527)
     at recaptcha__es.js: 534
     at recaptcha__es.js: 554

Screenshot:

![Captura clifrihos](https://user-images.githubusercontent.com/51704502/59269046-5f8e2680-8c4e-11e9-8a5c-1d9ccf339770.PNG)

Any solution?

**Comment by manuman94** [comment]
Same here, but in my website is happening only in Mozilla Firefox (although in the @Manuel-CJ 's screenshot is running Chrome).

Any solution to this?

**Comment by manuman94** [comment]
Well, I think I know why this is happening.

I've reviewed the module's code and I see that there is a javascript code that waits until the document is fully loaded and appends the placeholder element into the DOM. This is intended to happen before Google Recaptcha library is loaded by the browser.

The thing is that sometimes (in some browsers, browser versions or slow PCs) Google Recaptcha Library is loaded first and it doesn't find the placeholder element because actually it doesn't exists and moments later the first javascript code appends it, but it's late.

I think this plugin had to make use of the hooks and load the placeholder element with the first load of the page so this error wouldn't happen.

A possible workaround is to place the placeholder element in the TPL template where you want to put the captcha and comment/delete the javascript that appends it at the DOM.

Greetings.

**Comment by nenes25** [comment]
@manuman94 your analysis seems to be a good explanation.

I've effectualy choose to add the content dynamically with javascript because it allows non avanced users not to edit templates files.

 As no hooks exists on the contact form webpage, i have no other option
 ( The first version of this module worked this way)

For now i've unfortunalely no automatic options to fix this behaviour
