### ISSUE TITLE
PS 1.7.6.1 and eicaptcha V2.0.5 Problems

### ISSUE THREAD

**Issue by HartLarsson** [nenes25/eicaptcha#128]
** Prestashop Version **
1.7.6.1

** Eicaptcha version **
2.0.5

** Do you use a specific theme **
Alysum

**Describe the bug**
The module cannot be correctly installed

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/135f45d34ec5231d0404ced16a6a9451/raw)](https://gyazo.com/135f45d34ec5231d0404ced16a6a9451)

**Additional context**
the 2.0.5 is the latest version downlodable, so probably there is some incompatibility with PS 1.7.6.1?

**Comment by nenes25** [comment]
Hi @HartLarsson,

In fact it's not a problem, the module use composer to manage dependencies as written in the red block.
You should have download the zip directly from github repository.
In order to get a module which works you have to download to last release from here : https://github.com/nenes25/eicaptcha/releases/tag/2.0.4 
or to run the composer install command in your directory as written ;)

Regards,

**Comment by HartLarsson** [comment]
thanks!
i do d/l the 2.0.4 and works!

**Comment by jbcorsu** [comment]
Merci grâce a ces détail je viens de réussir.
Merci encore.
