### ISSUE TITLE
Error! Cant perform action on eicaptcha. Not possible to install override: The method initContent in the class AuthController isalready overwritten by module onepagecheckoutps version 3.0.0

### ISSUE THREAD

**Issue by mwfurio** [nenes25/eicaptcha#146]
**Prestashop Version**  
1.7.5.1

**Eicaptcha version**  
Eicaptcha version - latest

**Do you use a specific theme**  
Yes, eletric

**Describe the bug**  
installing without problems but when i want to enable i get the error cant install overwrite, already overwritten by onepagecheckout v.3

**Screenshots**  

**Additional context**

**Comment by nenes25** [comment]
Hi,
The problem is clear, the file AuthController.php is already overwrite by another module.
So you'll have to put the override manualy
remove the directory override/controller/front/ from module and apply the code from the file 
 https://github.com/nenes25/eicaptcha/blob/17/override/controllers/front/AuthController.php

Regards,

**Comment by mwfurio** [comment]
Thanks for the reply, where to apply the code? Sorry iam not a pro in this but i can edit files and stuff.

**Comment by nenes25** [comment]
Hi,

I dont' know what your installed module make in the override.

But you should try to insert the code of link of my previous message in your local override/controller/front/AuthController.php file
( Do it in a dev environment , to be sure everything works fine )

Regards,
