### ISSUE TITLE
Captcha not required on forms

### ISSUE THREAD

**Issue by usuenapal** [nenes25/eicaptcha#174]
**Prestashop Version**  
1.7.7.0

**Eicaptcha version**  
2.0.7

**Do you use a specific theme**  
Movic

**Describe the bug**  
The captcha is added to the form but is not being required when sending the form. I can send the forms without checking the captchas.

**Screenshots**  

**Additional context**  
I use the module in contact and register forms and also, I'm adding the captcha manually to a newsletter form in main page.

**Comment by nenes25** [comment]
Hello,

Could you please tell me if the issue is only on the captcha you add on the newsletter form ?
Or also in customer create form and contact form ?

I've done a fix for version 1.7.7 a couple of weeks ago in the line : 
https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L368 
But depending the themes it could fail.

Regards,

**Comment by usuenapal** [comment]
Hi!!

Thanks for the answer. The issue happens in all the forms, the one added manually and the ones added by the module. I tried to delete the manually added form in order to check if that is generating the issue, but it remains. 

I will try the update and let you know.

Thank you very much in advance!!
