### ISSUE TITLE
The captcha is not visible in the registration form

### ISSUE THREAD

**Issue by davidlambda** [nenes25/eicaptcha#176]
Hello,

I have installed the module Eicaptcha in my prestashop, it works correctly in the contact form of my Contact page (Contact Form module) but it does not show in my account registration form. What can be the motive?

**Comment by davidlambda** [comment]
I have tried to install version 2.0.6 to check if it works, but no, since version 2.0.7 still does not work the captcha in the registration form. I need an answer please, it is a long time without feedback.

**Comment by nenes25** [comment]
Hello,

In order to let me know about your issue please fill the following template :  ( It should have been asked automatically but the feature was missing on last 2 weeks )

With your current details i'm unfortunately unable to help.

Furthermore i want to precise that I really dislike the comments like your last...
Because this module is free and i help people on my free time without any benefits on it.
So if you **need** something you should rather buy a module instead of using  a free module.

**Prestashop Version**  
Your prestashop version

**Eicaptcha version**  
Eicaptcha version

**Do you use a specific theme**  
Are you using a specific theme, if yes please tell which

**Describe the bug**  
A clear and concise description of what the bug is.

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Additional context**  
Add any other context about the problem here.

**Comment by davidlambda** [comment]
I'm sorry to have offended you, it was not my goal, I just want to solve this problem with my website which makes my website not functional.

Ok, I write the details below:

**Prestashop Version**
1.7.2.4

**Eicaptcha version**
2.0.7

**Do you use a specific theme**
Jms_deermarket (version 1)

**Describe the bug**
The Google captcha is displayed correctly in the contact form but is not displayed in the user registration form.

**Screenshots**
- Contact form
![image](https://user-images.githubusercontent.com/45964547/110457271-c0b88780-80ca-11eb-9fb0-57b770011027.png)
- Register form
![image](https://user-images.githubusercontent.com/45964547/110457445-f0678f80-80ca-11eb-8c6c-1cd26fa72824.png)


**Additional context**
I have tried to install the Eicaptcha module both version 2.0.6 and 2.0.7, but both versions the same problem occurs.

**Comment by nenes25** [comment]
Hello,

Thanks for the feedback, as i don't know this theme, could you please give me an url to check ?

Best Regards,

**Comment by davidlambda** [comment]
- Contact form: https://www.obdcenter.com/es/contactenos
- Register form: https://www.obdcenter.com/es/iniciar-sesion?create_account=1

**Comment by nenes25** [comment]
Is the hook displayCustomerAccountForm available and displayed in your theme ?
And is the module well registered on it ?
You can check in the module configuration in back office.
And in the "Position" link in the appearance section

![image](https://user-images.githubusercontent.com/7163132/110469120-886c7580-80d9-11eb-8f9f-76062e872182.png)

**Comment by davidlambda** [comment]
>Is the hook displayCustomerAccountForm available and displayed in your theme ?

Yes
![image](https://user-images.githubusercontent.com/45964547/110470590-54924f80-80db-11eb-88d7-fdbb9ace5342.png)

>And is the module well registered on it ?

Yes, it is well registered

![image](https://user-images.githubusercontent.com/45964547/110471657-adaeb300-80dc-11eb-83fb-c219319356b4.png)

![image](https://user-images.githubusercontent.com/45964547/110471183-1e090480-80dc-11eb-83a7-8904227abfce.png)


Even though I have noticed that the versions do not match, can that be the problem?

v2.0
![image](https://user-images.githubusercontent.com/45964547/110471364-59a3ce80-80dc-11eb-8493-fa23338a7b6b.png)

v2.0.7
![image](https://user-images.githubusercontent.com/45964547/110471109-03369000-80dc-11eb-8dc6-478e44821ad3.png)

**Comment by nenes25** [comment]
Thanks everything seems good in the configuration.
But the content of the hook is not displayed for the module, and this is why it is not working.
If you search for "g-recaptcha" in the page it founds nothing even if the text is well in the module template.
So i guess that the issue is related with the display of the hook **displayCustomerAccountForm**
Coud you please check in your theme in themes/*yourtheme*/templates/customer/_partials/customer-form.tpl
![image](https://user-images.githubusercontent.com/7163132/110473845-46dec900-80df-11eb-90eb-aa2b1e8ddef0.png)

You can also try to add a die text in order to check if the module hook is well called

![image](https://user-images.githubusercontent.com/7163132/110474000-74c40d80-80df-11eb-9a4a-cb5187a01c7e.png)


Regards,

**Comment by davidlambda** [comment]
I have added this line of code `{$ hook_create_account_form nofilter}` in `public_html / themes / jms_deermarket / templates / customer / _partials / customer-form.tpl` and it works for me perfectly! Captcha is already displayed and it works fine.

Thank you very much for your help!

All the best.

**Comment by nenes25** [comment]
Thanks for the feedback, so nothing related with my module.
If you can share this with your theme provider it will certainly avoid other issues related with this hook ;)

Best regards,
