### ISSUE TITLE
No captcha validation in the personal data form (customer account)

### ISSUE THREAD

**Issue by Fera** [nenes25/eicaptcha#238]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

I'm using at_movic, but the same error occurs in the default template

### Describe the bug

Captcha unnecessarily appears in the Customer's account in Personal Data - it is not validated there anyway

**Comment by nenes25** [comment]
Hello,

Could you please provide an url to check ?

Regards,

**Comment by Fera** [comment]
> Hello,
> 
> Could you please provide an url to check ?
> 
> Regards,

[https://demo2.ferart.pl](https://demo2.ferart.pl)

**Comment by nenes25** [comment]
Hello,
Thanks for the url
Unfortunately this website is restricted, so i can't check.

Regards,

**Comment by Fera** [comment]
> Hello, Thanks for the url Unfortunately this website is restricted, so i can't check.
> 
> Regards,

It's working now. Sorry, I had the shop down because it's under construction

**Comment by nenes25** [comment]
Hello,

Thanks for opening your website.
The issue is related with your theme that should implement some custom hooks.
I've never tested the module with leo themes.

On the default register page, the captcha is displayed as expected.
https://demo2.ferart.pl/pl/logowanie?create_account=1

I well see the captcha in the customer information page, but i am not able to reproduce the issue on a default theme.

![image](https://user-images.githubusercontent.com/7163132/206388568-f9306175-df09-411b-8b1d-9f0015f6d5d8.png)

In order to fix this issue you can add the condition  
`if (Configuration::get('CAPTCHA_ENABLE_ACCOUNT') == 1 && $this->context->controller->php_self == 'authentication') { `
here https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L271

And after that it will not be displayed anymore on your page.

Regards,

**Comment by Fera** [comment]
> Hello,
> 
> Thanks for opening your website. The issue is related with your theme that should implement some custom hooks. I've never tested the module with leo themes.
> 
> On the default register page, the captcha is displayed as expected. https://demo2.ferart.pl/pl/logowanie?create_account=1
> 
> I well see the captcha in the customer information page, but i am not able to reproduce the issue on a default theme.
> 
> ![image](https://user-images.githubusercontent.com/7163132/206388568-f9306175-df09-411b-8b1d-9f0015f6d5d8.png)
> 
> In order to fix this issue you can add the condition `if (Configuration::get('CAPTCHA_ENABLE_ACCOUNT') == 1 && $this->context->controller->php_self == 'authentication') { ` here https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L271
> 
> And after that it will not be displayed anymore on your page.
> 
> Regards,

On the default template, there is exactly the same situation in the Customer's account in the information section. I checked it on a fresh installation without any other templates and modules installed. 

Your solution also removes the Captcha in the first step of thecheckout, and it is validated there. Cannot register.

**Comment by nenes25** [comment]
OK so we can consider the problem from the other side and add condition such as 

`if (Configuration::get('CAPTCHA_ENABLE_ACCOUNT') == 1 && $this->context->controller->php_self != 'identity'`

But i've tried again on a fresh instance and i have not your behavior, the captcha is not displayed on this page with default configuration and theme.

Regards,

**Comment by Fera** [comment]
It's not about hiding it, it's about having valid validation if it already appears there. Hiding in css is the fastest if the captcha isn't validated anyway.
