### ISSUE TITLE
Error: initContent

### ISSUE THREAD

**Issue by Joaq82** [nenes25/eicaptcha#246]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Classic

### Describe the bug

Error actived module: No se pudo enable módulo eicaptcha. No se puede instalar la sobrecarga: El método initContent en la clase AuthController ha sido sobreescrito por el módulo onepagecheckoutps versión 4.1.6.

### Screenshots

Error text actived module.

### Additional context

Module one page

**Comment by nenes25** [comment]
Hello,

The error message is pretty clear.  
The module cannot be installed because another module have already rewrite a function that this module need to change.
_initContent_ of class _AuthController_

As I don't know what's this module is doing i cannot be sure of the fix.
But you will have to do it manually, it's not an issue of this module.

To do so.
Rename the file modules/eicaptcha/override/controllers/front/_AuthController.php_ to _AuthController.php.disabled_ 
This will prevent the installation of the content of this file, and will fix the module installation error.
And after that you need to take the content of the function and to merge with the content of your file override/controllers/front/AuthController.php

Regards,

**Comment by Joaq82** [comment]
ok, thanks!
