### ISSUE TITLE
"We detected that your site is not verifying reCAPTCHA solutions"

### ISSUE THREAD

**Issue by oilvier** [nenes25/eicaptcha#33]
### Your prestashop version
1.4.0.17

### Eicaptcha Version
v0.3.1

### Do you use a specific theme
Yes, custom made

### Issue description

Hi, 

I've got this message in the reCaptcha admin site : 

> We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see our developer site for more information.

However, the plugin seems to work (reCaptcha is visible on the contact form and my spam problem almost disappeared)

**Comment by nenes25** [comment]
Hello,

Thanks for your feedback.
This module version haven't been updated since about 3 years .

The recaptcha api may have change since, and errors may be linked with that.

Unfortunately i didn't plan any upgrade on this version for now , as i've already a lot of things to do on the others versions.
And prestashop 1.4 is not a priority.

I let the issue open if someone got time to fix it Quick, otherwise i'll see


Regards,

**Comment by oilvier** [comment]
Yes, I guess it's difficult to maintain a plugin for such an old version :/

Thanks for your answer

**Comment by nenes25** [comment]
you're welcome.
Sorry to not have enough time to fix it quick :-/

**Comment by dandumit** [comment]
I had the same issue. I have chosen recapcha 2 and now it's ok ! 
(implicit it's recapcha 3 )
