### ISSUE TITLE
Prevent repost form

### ISSUE THREAD

**Issue by 84pixels** [nenes25/eicaptcha#5]
Hello,

Our module does not work (contact form) when form refresh/repost data submited.

Regards,

**Comment by nenes25** [comment]
Hello,

Thanks for your feeback, i'll check this behaviour asap.

Regards,

**Comment by nenes25** [comment]
Hello,
I've tried and check no specific problem.

You need to check the captcha again if the contact form data was not all filled.
But it's due to prestashop default variables check, which is done in php and need page reload.
I cannot change this.

Could you please be more specific if the problem is not this ?

Regards
