### ISSUE TITLE
Captcha not showing on Internet Explorer 11

### ISSUE THREAD

**Issue by gcorbesier** [nenes25/eicaptcha#64]
### Your prestashop version
1.7.2.4

### Eicaptcha Version
2.0.5

### Do you use a specific theme
Volga Theme

### Issue description
Contactform does not show captcha in Internet Explorer 11. It works fine on Microsoft Edge, Google Chrome and Firefox.

URL
https://www.computercentrale.be/en/contact-us

**Comment by nenes25** [comment]
Hello,

This issue is related to your website.
If you open the debug console in IE 11, there is a javascript error.

![image](https://user-images.githubusercontent.com/7163132/39824442-a1433134-53af-11e8-843b-ddaf1a330cac.png)

I've tested with success the recaptcha display with IE 11 on my demo website.

Regards,

**Comment by gcorbesier** [comment]
I had to disable Smart Cache for Java Script, it is indeed general IE11 problem with PS 1.7, not the module.

However I found a small bug in hookDisplayCustomerAccountForm.tpl for 1.7 branch

Second last line should be (there is a right parenthesis too much currently which gives an error):
<script src="https://www.google.com/recaptcha/api.js{if isset($captchaforcelang)}?hl={$captchaforcelang}{/if}" async defer></script>
